# Generated by Django 4.1.2 on 2022-10-18 08:26

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=50, verbose_name='Title')),
                ('about_subtitle', models.TextField(max_length=200, verbose_name='Subtitle')),
                ('about_text', models.TextField(max_length=500, verbose_name='Text')),
                ('about_image', models.ImageField(upload_to=main_page.models.About.get_file_name, verbose_name='Photo')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
