# Generated by Django 4.1.2 on 2022-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_position', models.SmallIntegerField()),
                ('plan_title', models.CharField(max_length=50, verbose_name='Title')),
                ('plan_price', models.PositiveIntegerField(verbose_name='Plan price')),
                ('plan_list1', models.CharField(max_length=100, verbose_name='Lst1')),
                ('plan_list2', models.CharField(blank=True, max_length=100, verbose_name='Lst2')),
                ('plan_list3', models.CharField(blank=True, max_length=100, verbose_name='Lst3')),
                ('plan_list4', models.CharField(blank=True, max_length=100, verbose_name='Lst4')),
                ('plan_list5', models.CharField(blank=True, max_length=100, verbose_name='Lst5')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ('plan_position',),
            },
        ),
    ]
