# Generated by Django 4.1.2 on 2022-10-21 09:23

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whyus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_position', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('why_icon', models.ImageField(upload_to=main_page.models.Whyus.get_file_name, verbose_name='Icon')),
                ('why_title', models.CharField(max_length=50, verbose_name='Title')),
                ('why_about', models.TextField(max_length=250, verbose_name='About')),
            ],
            options={
                'verbose_name': 'Why us',
                'verbose_name_plural': 'Why us',
                'ordering': ('why_position',),
            },
        ),
    ]
