# Generated by Django 4.1.2 on 2022-10-17 11:38

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_position', models.SmallIntegerField()),
                ('feature_title', models.CharField(max_length=50, verbose_name='Title')),
                ('feature_about', models.TextField(max_length=200, verbose_name='About')),
                ('feature_image', models.ImageField(upload_to=main_page.models.Feature.get_file_name, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Feature',
                'ordering': ('feature_position',),
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=50, verbose_name='Name')),
                ('hero_about', models.TextField(max_length=100, verbose_name='About')),
                ('hero_image', models.ImageField(upload_to=main_page.models.Hero.get_file_name, verbose_name='Photo')),
                ('hero_access', models.BooleanField(default=True, verbose_name='Acces')),
            ],
        ),
    ]
